/*
 * File: app/view/genresPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoundCloud.view.genresPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.genrespanel',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.tab.Tab'
    ],

    itemId: 'genresPanel',
    title: 'Genres',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'electronicGrid',
                    title: 'Electronic',
                    forceFit: true,
                    store: 'GenreList',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'title',
                            text: 'Title',
                            flex: 2
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'user',
                            text: 'Artist',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            displayInfo: true,
                            store: 'GenreList'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    itemId: 'rockGrid',
                    title: 'Rock',
                    forceFit: true,
                    store: 'GenreList',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'title',
                            text: 'Title',
                            flex: 2
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'user',
                            text: 'Artist',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            displayInfo: true,
                            store: 'GenreList'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});