/*
 * File: app/view/homePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoundCloud.view.homePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.homepanel',

    requires: [
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    itemId: 'homePanel',
    layout: 'border',
    title: 'Home',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'homeToolbar',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 2,
                            itemId: 'searchfield',
                            emptyText: 'Search'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            itemId: 'songsGrid',
                            width: 904,
                            store: 'Songs',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 242,
                                    dataIndex: 'title',
                                    text: 'Title',
                                    flex: 2
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'user',
                                    text: 'Artist',
                                    flex: 1
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    itemId: 'pagingtoolbar',
                                    displayInfo: true,
                                    store: 'Songs'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});