/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoundCloud.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'SoundCloud.view.homePanel',
        'SoundCloud.view.genresPanel',
        'SoundCloud.view.uploadPanel',
        'SoundCloud.view.playlistPanel',
        'SoundCloud.view.detailsPanel',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel'
    ],

    itemId: 'mainView',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    height: 150,
                    itemId: 'mainContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            frame: true,
                            itemId: 'menuPanel',
                            width: 150,
                            collapseDirection: 'left',
                            collapsed: true,
                            collapsible: true,
                            title: 'Menu',
                            items: [
                                {
                                    xtype: 'menu',
                                    floating: false,
                                    itemId: 'menu',
                                    collapseFirst: false,
                                    collapsible: false,
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            itemId: 'home',
                                            text: 'Home'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            itemId: 'upload',
                                            text: 'Upload'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            itemId: 'genres',
                                            text: 'Genres'
                                        }
                                    ],
                                    listeners: {
                                        click: {
                                            fn: me.onMenuClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 2,
                            itemId: 'contentPanel',
                            layout: 'card',
                            bodyBorder: false,
                            items: [
                                {
                                    xtype: 'homepanel'
                                },
                                {
                                    xtype: 'genrespanel'
                                },
                                {
                                    xtype: 'uploadpanel'
                                }
                            ]
                        },
                        {
                            xtype: 'playlistpanel',
                            flex: 2
                        }
                    ]
                },
                {
                    xtype: 'detailspanel',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});