/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'Song'
    ],
    stores: [
        'Playlist',
        'GenreList'
    ],
    views: [
        'MainView',
        'homePanel',
        'genresPanel',
        'uploadPanel',
        'detailsPanel',
        'playlistPanel'
    ],
    controllers: [
        'Navigation',
        'Songs'
    ],
    name: 'SoundCloud',

    launch: function() {
        Ext.create('SoundCloud.view.MainView');
        SC.initialize({
          client_id: '6c6a48a95b3175e4270cfa0027d7d3ca',
          redirect_uri: 'http://127.0.0.1:9003/'
        });
    }

});
