/*
 * File: app/controller/Songs.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoundCloud.controller.Songs', {
    extend: 'Ext.app.Controller',

    statics: {
        playTrack: function(record) {
            SC.oEmbed(record.data.permalink_url, playOptions, document.getElementById('player'));

            setTimeout(function(){
                var widgetIframe = document.getElementById('player').getElementsByTagName('iframe')[0];
                var widget  = SC.Widget(widgetIframe);

                widget.bind(SC.Widget.Events.READY, function() {
                    console.log('entro ready');
                    widget.bind(SC.Widget.Events.PLAY, function() {
                        // get information about currently playing sound
                        console.log('track started');
                    });
                    widget.bind(SC.Widget.Events.FINISH, function() {
                        console.log('track finished');
                    });
                });

            },2000);
        }
    },

    stores: [
        'Songs'
    ],

    refs: [
        {
            ref: 'songsGrid',
            selector: '#songsGrid'
        },
        {
            ref: 'detailsPanel',
            selector: '#detailsPanel'
        },
        {
            ref: 'playlistGrid',
            selector: '#playlistGrid'
        }
    ],

    onSearchfieldEnter: function(field, e, eOpts) {
        if (e.getKey() == e.ENTER) {
            console.log(field.getValue() + ' was entered');
            var grid = this.getSongsGrid();
            grid.store.load({
                params: {
                    q: field.getValue(),
                    page: 1,
                    start: 0,
                    limit: 25
                }
            });
        }
    },

    onSongsGridSelect: function(rowmodel, record, index, eOpts) {
        var grid = this.getPlaylistGrid();
        grid.store.add(record);
    },

    onPlaylistGridSelect: function(dataview, record, item, index, e, eOpts) {
        var detailsPanel = this.getDetailsPanel(),
            playOptions = {
                auto_play: true,
                buying: false,
                liking: false,
                sharing: false,
                show_comments: false
            };
        var grid = this.getPlaylistGrid();
        console.log('index of record: ' + grid.store.data.indexOf(record));
        playTrack(record);

    },

    onPlaylistGridItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        e.stopEvent();
        this.ctxMenu = Ext.create('Ext.menu.Menu', {
            items:[{
                text: 'Remove from playlist'
            }],
            defaults: {
                listeners: {
                    click: function(item) {
                        this.getPlaylistGrid().store.remove([record]);
                        this.getPlaylistGrid().store.filter();
                    },
                    scope: this
                }
            }
        });

        this.ctxMenu.showAt(e.getXY());
    },

    init: function(application) {
        this.control({
            "#searchfield": {
                specialkey: this.onSearchfieldEnter
            },
            "#songsGrid": {
                select: this.onSongsGridSelect
            },
            "#playlistGrid": {
                itemdblclick: this.onPlaylistGridSelect,
                itemcontextmenu: this.onPlaylistGridItemContextMenu
            }
        });
    }

});
